# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1487097380);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1487097999);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1487204175);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1487204415);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1487204295);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1487098119);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 36);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1487204065850");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1487205827850");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1487204066049");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1487207666049");
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20170126195238");
user_pref("browser.slowStartup.averageTime", 3013);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20170126195238");
user_pref("browser.startup.homepage_override.mstone", "45.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":4}");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1487183299929");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1487096961685");
user_pref("datareporting.policy.firstRunTime", "1487096899928");
user_pref("datareporting.sessions.current.activeTicks", 56);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2472);
user_pref("datareporting.sessions.current.main", 720);
user_pref("datareporting.sessions.current.sessionRestored", 2881);
user_pref("datareporting.sessions.current.startTime", "1487204053599");
user_pref("datareporting.sessions.current.totalTime", 384);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1487096898056,\"a\":34,\"t\":543,\"c\":false,\"m\":721,\"fp\":3463,\"sr\":3368}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1487097877127,\"a\":2,\"t\":2700,\"c\":true,\"m\":710,\"fp\":2945,\"sr\":3173}");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"loop@mozilla.org\":{\"version\":\"1.1.14\",\"type\":\"extension\",\"descriptor\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10sBlockedByAddons", false);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:45.7.0");
user_pref("extensions.getAddons.cache.lastUpdate", 1487097380);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "45.7.0");
user_pref("extensions.lastPlatformVersion", "45.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"loop@mozilla.org\":{\"d\":\"/usr/lib64/firefox/browser/features/loop@mozilla.org.xpi\",\"e\":true,\"v\":\"1.1.14\",\"st\":1485461158000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"45.7.0\",\"st\":1485461157000}}}");
user_pref("gecko.buildID", "20170126195238");
user_pref("gecko.mstone", "45.7.0");
user_pref("gfx.crash-guard.glcontext.appVersion", "45.7.0");
user_pref("gfx.crash-guard.glcontext.deviceID", "Gallium 0.4 on llvmpipe (LLVM 3.8, 128 bits)");
user_pref("gfx.crash-guard.glcontext.driverVersion", "2.1 Mesa 11.2.2");
user_pref("gfx.crash-guard.status.glcontext", 1);
user_pref("idle.lastDailyNotification", 1487097160);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1487096964);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20170126195238");
user_pref("media.gmp-manager.lastCheck", 1487204116);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.database.lastMaintenance", 1487097160);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1487097160);
user_pref("toolkit.startup.last_success", 1487204054);
user_pref("toolkit.telemetry.cachedClientID", "091a6f19-be28-4786-a8ab-a1a0aab1cfd1");
user_pref("toolkit.telemetry.previousBuildID", "20170126195238");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
